### ISSUE TITLE
[Suggestion] Option for fairGTrackJsonValidate.py to fail if validation fails

### ISSUE THREAD

**Issue by dtitov** [fairtracks/fairtracks_validator#13]
Right now `fairGTrackJsonValidate.py` doesn't fail if validation fails (it always returns zero exit code). It would be nice to have some flag like `failOnError` that would make this script "fail" if validation fails (this is very useful for the CI pipeline that we are developing right now).

**Comment by jmfernandez** [comment]
The command-line client was already using UNIX exit code 1 whenever all the found JSON Schemas had problems. Since commit f4146d7995192485f5aa5b5c719d5c2cf7ef0d1e the command-line client is also using UNIX exit code 2 to signal some of the JSON contents had validation errors against the loaded JSON Schemas.
